spring:
    application:
        name: myshop
        admin:
            enabled: true
            jmx-name: com.example.myshop:type=MyShopAdmin
    config:
        on-not-found: ignore
    profiles:
        default: local
    lifecycle:
        timeout-per-shutdown-phase: 35s # 기본값은 30s 이다.

server:
    port: 9090
    shutdown: graceful  # graceful shutdown 적용 (immediate 옵션도 존재하는 해당 옵션은 디폴트이며 말 그대로 즉시 종료이다.)


# 패키지와 그 하위 로그 레벨 설정 (디폴트 값은 info)
logging:
  level:
    springboot.MVCBasic: debug 		#springboot.MVCBasic 패키지의 하위 레벨 설정
